// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 15.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Positivtest2 - Verwenden Sie "Positivtest2Params", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void Positivtest2()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILb120_2_BibliothekexListItem.UINameEdit;
            WpfButton uIAusleihenButton = this.UIMainWindowWindow.UIAusleihenButton;
            WpfText uIAforbeginnersText = this.UIMainWindowWindow.UIItemCustom.UIDataGridTable.UIItem85Row.UIAforbeginnersCell.UIAforbeginnersText;
            WpfCheckBox uIIstVerfügbarCheckBox = this.UIMainWindowWindow.UIScrollViewerPane.UIIstVerfügbarCheckBox;
            WpfButton uISpeichernButton = this.UIMainWindowWindow.UIScrollViewerPane.UISpeichernButton;
            WpfText uIGespeichertText1 = this.UIMainWindowWindow.UIItemCustom1.UIGespeichertText.UIGespeichertText1;
            WpfButton uIZurückButton = this.UIMainWindowWindow.UIScrollViewerPane.UIZurückButton;
            WinButton uISchließenButton = this.UIMainWindowWindow1.UISchließenButton;
            #endregion

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(228, 8));

            // Klicken "Ausleihen" Schaltfläche
            Mouse.Click(uIAusleihenButton, new Point(72, 12));

            // Doppelklicken "A# for beginners" Bezeichnung
            Mouse.DoubleClick(uIAforbeginnersText, new Point(38, 13));

            // "Ist Verfügbar" Kontrollkästchen auswählen
            uIIstVerfügbarCheckBox.Checked = this.Positivtest2Params.UIIstVerfügbarCheckBoxChecked;

            // Klicken "Speichern" Schaltfläche
            Mouse.Click(uISpeichernButton, new Point(26, 13));

            // Klicken "Gespeichert" Bezeichnung
            Mouse.Click(uIGespeichertText1, new Point(49, 10));

            // Klicken "Zurück" Schaltfläche
            Mouse.Click(uIZurückButton, new Point(41, 7));

            // Klicken "Schließen" Schaltfläche
            Mouse.Click(uISchließenButton, new Point(17, 17));
        }
        
        /// <summary>
        /// Negativtest - Verwenden Sie "NegativtestParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void Negativtest()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILb120_2_BibliothekexListItem.UINameEdit;
            WpfButton uIBücherButton = this.UIMainWindowWindow.UIBücherButton;
            WpfText uIAforbeginnersText = this.UIMainWindowWindow.UIItemCustom2.UIDataGridTable.UIItem166Row.UIAforbeginnersCell.UIAforbeginnersText;
            WpfDatePicker uIDtpStartDatePicker = this.UIMainWindowWindow.UIScrollViewerPane.UIDtpStartDatePicker;
            WpfDatePicker uIDtpEndDatePicker = this.UIMainWindowWindow.UIScrollViewerPane.UIDtpEndDatePicker;
            WpfComboBox uICbxKundeComboBox = this.UIMainWindowWindow.UIScrollViewerPane.UICbxKundeComboBox;
            WpfButton uISpeichernButton = this.UIMainWindowWindow.UIScrollViewerPane.UISpeichernButton;
            WpfText uIDatumüberschneidetsiText1 = this.UIMainWindowWindow.UIItemCustom1.UIGespeichertText.UIDatumüberschneidetsiText1;
            WpfButton uIZurückButton = this.UIMainWindowWindow.UIScrollViewerPane.UIZurückButton;
            WinButton uISchließenButton = this.UIMainWindowWindow1.UISchließenButton;
            #endregion

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(234, 10));

            // Klicken "Bücher" Schaltfläche
            Mouse.Click(uIBücherButton, new Point(78, 12));

            // Doppelklicken "A# for beginners" Bezeichnung
            Mouse.DoubleClick(uIAforbeginnersText, new Point(82, 10));

            // "06-Jun-2018" in "dtpStart" Datumsauswahl auswählen
            uIDtpStartDatePicker.DateAsString = this.NegativtestParams.UIDtpStartDatePickerDateAsString;

            // "01-Dec-2018" in "dtpEnd" Datumsauswahl auswählen
            uIDtpEndDatePicker.DateAsString = this.NegativtestParams.UIDtpEndDatePickerDateAsString;

            // "111" in "cbxKunde" Kombinationsfeld auswählen
            uICbxKundeComboBox.SelectedItem = this.NegativtestParams.UICbxKundeComboBoxSelectedItem;

            // Klicken "Speichern" Schaltfläche
            Mouse.Click(uISpeichernButton, new Point(44, 11));

            // Klicken "Datum überschneidet sich mit einer anderen Ausleih..." Bezeichnung
            Mouse.Click(uIDatumüberschneidetsiText1, new Point(81, 11));

            // Klicken "Zurück" Schaltfläche
            Mouse.Click(uIZurückButton, new Point(49, 13));

            // Klicken "Schließen" Schaltfläche
            Mouse.Click(uISchließenButton, new Point(23, 20));
        }
        
        #region Properties
        public virtual Positivtest2Params Positivtest2Params
        {
            get
            {
                if ((this.mPositivtest2Params == null))
                {
                    this.mPositivtest2Params = new Positivtest2Params();
                }
                return this.mPositivtest2Params;
            }
        }
        
        public virtual NegativtestParams NegativtestParams
        {
            get
            {
                if ((this.mNegativtestParams == null))
                {
                    this.mNegativtestParams = new NegativtestParams();
                }
                return this.mNegativtestParams;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UIMainWindowWindow1 UIMainWindowWindow1
        {
            get
            {
                if ((this.mUIMainWindowWindow1 == null))
                {
                    this.mUIMainWindowWindow1 = new UIMainWindowWindow1();
                }
                return this.mUIMainWindowWindow1;
            }
        }
        #endregion
        
        #region Fields
        private Positivtest2Params mPositivtest2Params;
        
        private NegativtestParams mNegativtestParams;
        
        private UIDebugWindow mUIDebugWindow;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UIMainWindowWindow1 mUIMainWindowWindow1;
        #endregion
    }
    
    /// <summary>
    /// An "Positivtest2" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class Positivtest2Params
    {
        
        #region Fields
        /// <summary>
        /// "Ist Verfügbar" Kontrollkästchen auswählen
        /// </summary>
        public bool UIIstVerfügbarCheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// An "Negativtest" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class NegativtestParams
    {
        
        #region Fields
        /// <summary>
        /// "06-Jun-2018" in "dtpStart" Datumsauswahl auswählen
        /// </summary>
        public string UIDtpStartDatePickerDateAsString = "06-Jun-2018";
        
        /// <summary>
        /// "01-Dec-2018" in "dtpEnd" Datumsauswahl auswählen
        /// </summary>
        public string UIDtpEndDatePickerDateAsString = "01-Dec-2018";
        
        /// <summary>
        /// "111" in "cbxKunde" Kombinationsfeld auswählen
        /// </summary>
        public string UICbxKundeComboBoxSelectedItem = "111";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UILb120_2_BibliothekexListItem UILb120_2_BibliothekexListItem
        {
            get
            {
                if ((this.mUILb120_2_BibliothekexListItem == null))
                {
                    this.mUILb120_2_BibliothekexListItem = new UILb120_2_BibliothekexListItem(this);
                }
                return this.mUILb120_2_BibliothekexListItem;
            }
        }
        #endregion
        
        #region Fields
        private UILb120_2_BibliothekexListItem mUILb120_2_BibliothekexListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UILb120_2_BibliothekexListItem : WinListItem
    {
        
        public UILb120_2_BibliothekexListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "lb120_2_Bibliothek.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UIAusleihenButton
        {
            get
            {
                if ((this.mUIAusleihenButton == null))
                {
                    this.mUIAusleihenButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIAusleihenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnAusleihe";
                    this.mUIAusleihenButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIAusleihenButton;
            }
        }
        
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIScrollViewerPane UIScrollViewerPane
        {
            get
            {
                if ((this.mUIScrollViewerPane == null))
                {
                    this.mUIScrollViewerPane = new UIScrollViewerPane(this);
                }
                return this.mUIScrollViewerPane;
            }
        }
        
        public UIItemCustom1 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom1(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public WpfButton UIBücherButton
        {
            get
            {
                if ((this.mUIBücherButton == null))
                {
                    this.mUIBücherButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIBücherButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnBook";
                    this.mUIBücherButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIBücherButton;
            }
        }
        
        public UIItemCustom2 UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new UIItemCustom2(this);
                }
                return this.mUIItemCustom2;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIAusleihenButton;
        
        private UIItemCustom mUIItemCustom;
        
        private UIScrollViewerPane mUIScrollViewerPane;
        
        private UIItemCustom1 mUIItemCustom1;
        
        private WpfButton mUIBücherButton;
        
        private UIItemCustom2 mUIItemCustom2;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.UC_Ausleihe";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDataGridTable : WpfTable
    {
        
        public UIDataGridTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "dataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem85Row UIItem85Row
        {
            get
            {
                if ((this.mUIItem85Row == null))
                {
                    this.mUIItem85Row = new UIItem85Row(this);
                }
                return this.mUIItem85Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem85Row mUIItem85Row;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItem85Row : WpfRow
    {
        
        public UIItem85Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfRow.PropertyNames.Name] = "85";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIAforbeginnersCell UIAforbeginnersCell
        {
            get
            {
                if ((this.mUIAforbeginnersCell == null))
                {
                    this.mUIAforbeginnersCell = new UIAforbeginnersCell(this);
                }
                return this.mUIAforbeginnersCell;
            }
        }
        #endregion
        
        #region Fields
        private UIAforbeginnersCell mUIAforbeginnersCell;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIAforbeginnersCell : WpfCell
    {
        
        public UIAforbeginnersCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Buchtitel";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIAforbeginnersText
        {
            get
            {
                if ((this.mUIAforbeginnersText == null))
                {
                    this.mUIAforbeginnersText = new WpfText(this);
                    #region Suchkriterien
                    this.mUIAforbeginnersText.SearchProperties[WpfText.PropertyNames.Name] = "A# for beginners";
                    this.mUIAforbeginnersText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIAforbeginnersText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIAforbeginnersText;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIScrollViewerPane : WpfPane
    {
        
        public UIScrollViewerPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "scrollViewer";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfCheckBox UIIstVerfügbarCheckBox
        {
            get
            {
                if ((this.mUIIstVerfügbarCheckBox == null))
                {
                    this.mUIIstVerfügbarCheckBox = new WpfCheckBox(this);
                    #region Suchkriterien
                    this.mUIIstVerfügbarCheckBox.SearchProperties[WpfCheckBox.PropertyNames.AutomationId] = "chkIsAvailable";
                    this.mUIIstVerfügbarCheckBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIIstVerfügbarCheckBox;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        
        public WpfButton UIZurückButton
        {
            get
            {
                if ((this.mUIZurückButton == null))
                {
                    this.mUIZurückButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIZurückButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnZurück";
                    this.mUIZurückButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIZurückButton;
            }
        }
        
        public WpfDatePicker UIDtpStartDatePicker
        {
            get
            {
                if ((this.mUIDtpStartDatePicker == null))
                {
                    this.mUIDtpStartDatePicker = new WpfDatePicker(this);
                    #region Suchkriterien
                    this.mUIDtpStartDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "dtpStart";
                    this.mUIDtpStartDatePicker.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIDtpStartDatePicker;
            }
        }
        
        public WpfDatePicker UIDtpEndDatePicker
        {
            get
            {
                if ((this.mUIDtpEndDatePicker == null))
                {
                    this.mUIDtpEndDatePicker = new WpfDatePicker(this);
                    #region Suchkriterien
                    this.mUIDtpEndDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "dtpEnd";
                    this.mUIDtpEndDatePicker.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIDtpEndDatePicker;
            }
        }
        
        public WpfComboBox UICbxKundeComboBox
        {
            get
            {
                if ((this.mUICbxKundeComboBox == null))
                {
                    this.mUICbxKundeComboBox = new WpfComboBox(this);
                    #region Suchkriterien
                    this.mUICbxKundeComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "cbxKunde";
                    this.mUICbxKundeComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICbxKundeComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfCheckBox mUIIstVerfügbarCheckBox;
        
        private WpfButton mUISpeichernButton;
        
        private WpfButton mUIZurückButton;
        
        private WpfDatePicker mUIDtpStartDatePicker;
        
        private WpfDatePicker mUIDtpEndDatePicker;
        
        private WpfComboBox mUICbxKundeComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemCustom1 : WpfCustom
    {
        
        public UIItemCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.UC_DetailedView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIGespeichertText UIGespeichertText
        {
            get
            {
                if ((this.mUIGespeichertText == null))
                {
                    this.mUIGespeichertText = new UIGespeichertText(this);
                }
                return this.mUIGespeichertText;
            }
        }
        #endregion
        
        #region Fields
        private UIGespeichertText mUIGespeichertText;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIGespeichertText : WpfText
    {
        
        public UIGespeichertText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfText.PropertyNames.AutomationId] = "lblStatus";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIGespeichertText1
        {
            get
            {
                if ((this.mUIGespeichertText1 == null))
                {
                    this.mUIGespeichertText1 = new WpfText(this);
                    #region Suchkriterien
                    this.mUIGespeichertText1.SearchProperties[WpfText.PropertyNames.Name] = "Gespeichert";
                    this.mUIGespeichertText1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIGespeichertText1.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIGespeichertText1;
            }
        }
        
        public WpfText UIDatumüberschneidetsiText1
        {
            get
            {
                if ((this.mUIDatumüberschneidetsiText1 == null))
                {
                    this.mUIDatumüberschneidetsiText1 = new WpfText(this);
                    #region Suchkriterien
                    this.mUIDatumüberschneidetsiText1.SearchProperties[WpfText.PropertyNames.Name] = "Datum überschneidet sich mit einer anderen Ausleihe";
                    this.mUIDatumüberschneidetsiText1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIDatumüberschneidetsiText1.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIDatumüberschneidetsiText1;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIGespeichertText1;
        
        private WpfText mUIDatumüberschneidetsiText1;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItemCustom2 : WpfCustom
    {
        
        public UIItemCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.UC_Buch";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable1 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable1(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable1 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIDataGridTable1 : WpfTable
    {
        
        public UIDataGridTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "dataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem166Row UIItem166Row
        {
            get
            {
                if ((this.mUIItem166Row == null))
                {
                    this.mUIItem166Row = new UIItem166Row(this);
                }
                return this.mUIItem166Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem166Row mUIItem166Row;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIItem166Row : WpfRow
    {
        
        public UIItem166Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfRow.PropertyNames.Name] = "166";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIAforbeginnersCell1 UIAforbeginnersCell
        {
            get
            {
                if ((this.mUIAforbeginnersCell == null))
                {
                    this.mUIAforbeginnersCell = new UIAforbeginnersCell1(this);
                }
                return this.mUIAforbeginnersCell;
            }
        }
        #endregion
        
        #region Fields
        private UIAforbeginnersCell1 mUIAforbeginnersCell;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIAforbeginnersCell1 : WpfCell
    {
        
        public UIAforbeginnersCell1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Buchtitel";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIAforbeginnersText
        {
            get
            {
                if ((this.mUIAforbeginnersText == null))
                {
                    this.mUIAforbeginnersText = new WpfText(this);
                    #region Suchkriterien
                    this.mUIAforbeginnersText.SearchProperties[WpfText.PropertyNames.Name] = "A# for beginners";
                    this.mUIAforbeginnersText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIAforbeginnersText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIAforbeginnersText;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UIMainWindowWindow1 : WinWindow
    {
        
        public UIMainWindowWindow1()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WinButton UISchließenButton
        {
            get
            {
                if ((this.mUISchließenButton == null))
                {
                    this.mUISchließenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUISchließenButton.SearchProperties[WinButton.PropertyNames.Name] = "Schließen";
                    this.mUISchließenButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISchließenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISchließenButton;
        #endregion
    }
}
