//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB120_02.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class M120Datenbank : DbContext
    {
        public M120Datenbank()
            : base("name=M120Datenbank")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
        public virtual DbSet<Kunde_Reise> Kunde_Reise { get; set; }
        public virtual DbSet<Land> Land { get; set; }
        public virtual DbSet<Reise> Reise { get; set; }
        public virtual DbSet<Reise_Hotel> Reise_Hotel { get; set; }
        public virtual DbSet<HotelBild> HotelBild { get; set; }
    }
}
